### ISSUE TITLE
Add support for external ids to update a model (or perhaps add more docs example)

### ISSUE THREAD

**Issue by nekopep** [katyukha/openerp-proxy#11]
I've started to use your very usefull library to push data programmatically to my odoo instance and I found it very convenient.
I also use another library https://github.com/tfrancoi/odoo_csv_import that use extensively xml_id (what I think you call external id) to be able to push data and later update them.

I would like to use the same mechanism with openerp-proxy, but I can't find any documentation hint on the way to do this.

Here is an example usage:
I create a sale order with a specific "name" and because my import is not perfect, I would like to relaunch the "create" command with updated parameters. With odoo_csv_import because all is referenced with xml_id, updating data update the "old" data, while currently with openerp-proxy it create a new odoo id, so I get 2 sale.order with same name but with 2 different internal id.

Do you think it could be possible to make something like this with your lib?

I'll try to study code from "odoo_csv_import" to see how xml_id is handled but, wondering if you could tell me a quick fix? I'm willing to help update the doc also.

**Comment by nekopep** [comment]
I digged into odoo_csv_import code, and I found the rpc call:
result = self.connection.get_service('object').execute_kw(
                                                    self.connection.database,
                                                    self.connection.user_id,
                                                    self.connection.password,
                                                    self.model_name,
                                                    method,
                                                    args, kw)
The method used is "load" and args[0] is a list of data name (ex ["id","name","partner_id",...] and args[1] is a list of data to import example: [["ext_S0001","S0001",1,...],["ext_S0002","S0002",1,..]
["id"] seems to be the external id (xml_id).
I think I can do the same with odoo proxy. Perhaps we could mimic odoo csv import to add an import  plugin.

**Comment by nekopep** [comment]
Well, I close this issue.
I manage to do what I need, searching first with search_read if a previous sale.order has been created.
I tried to mimic "odoo_csv_import", that is not the purpose of this lib.
Sorry for the noise.

**Comment by katyukha** [comment]
Hi,

There is a plugin [external_ids](https://odoo-rpc-client.readthedocs.io/en/latest/module_ref/odoo_rpc_client.plugins.html#module-odoo_rpc_client.plugins.external_ids) that provides some utility functions to work with xmlids.

Also, you can call `load` method of model directly:

```python
cl = Client()
cl['my.model'].load(fields, data)
```

You can call any model's method decorated with `multi` or `model` directly like example below:

```python
>>> move_obj = db['stock.move']
>>> move = move_obj.browse(1234)
>>> move.state
... 'confirmed'
>>> move.check_assign()   # call move's method
>>> move.refresh()
>>> move.state
... 'assigned'
>>> move.picking_id
... R('stock.picking', 12)['OUT-12']
>>> move.picking_id.id
... 12
>>> move.picking_id.name
... 'OUT-12'
>>> move.picking_id_.state
... 'assigned'
```

Also, there is [ref](https://odoo-rpc-client.readthedocs.io/en/latest/module_ref/odoo_rpc_client.html#odoo_rpc_client.client.Client.ref) method of `Client`, that returns record by xmlid

We at [CR&D](https://github.com/crnd-inc/) have one more project that may be interesting for you: [odoo_transfer_lib](https://github.com/crnd-inc/odoo-transfer-lib) - library that have to be used within Jupyter Notebook to declaratively transfer selected data from one Odoo database to another.

Hope, this answer will help you)

**Comment by nekopep** [comment]
Interesting, thanks for your feedback. I'm moving form one different erp to odoo. (so I have tons of excel files)
+1 for external_ids.
I'm just missing one thing, do you know how I could create an external id?
I mean should I load "ir.model.data" directlt and hack it, or perhaps there is a "simpler" way?
