### ISSUE TITLE
Using sudo() via client

### ISSUE THREAD

**Issue by RodolfoLima** [katyukha/openerp-proxy#12]
Hi,

I would like to know if it is possible to use sudo() via this client, like to change a user performing an action?

In Odoo v12: self.env['model_obj'].sudo(user_id).method()

I searched in the documentation and tried a few things but couldn't make it work.

Do you have an example?

Thank you in advance for the help

**Comment by jpoa** [comment]
I think the project moved to here: https://github.com/katyukha/odoo-rpc-client

**Comment by katyukha** [comment]
Hi,

First, there is no way to use sudo via RPC.
Second, `odoo-rpc-client` is the core project that imlements xmlrcp/jsonrpc for odoo, and this `openerp-proxy` is just IPython / Jupyter integration (interface) for `odoo-rpc-client` with set of extensions and plugins that introduce more features useful in IPython / Jupyter environment. Originally this project was used to inspect odoo databases and do basic data analysis via Jupyter or IPython.
