### ISSUE TITLE
Error on release 0.6.5

### ISSUE THREAD

**Issue by agb80** [katyukha/openerp-proxy#4]
After upgrade to release 0.6.5 I got follow error running openerp_proxy:

```
  File "bin/openerp_proxy", line 46, in <module>
    main()
  File "/home/agustin/.buildout/eggs/openerp_proxy-0.6.5-py2.7.egg/openerp_proxy/main.py", line 54, in main
    max_aliase_len = max((len(i) for i in session.aliases))
ValueError: max() arg is an empty sequence
```

I'm not using any alias currently, and using buildot for install the package.

**Comment by katyukha** [comment]
Thanks for filing issue! New version with this fix will be released in few days!
